# Generated by Django 5.2 on 2026-04-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="role",
            field=models.CharField(
                choices=[("customer", "Клиент"), ("coach", "Тренер")],
                db_index=True,
                default="customer",
                max_length=30,
                verbose_name="роль",
            ),
        ),
    ]
