# Generated by Django 5.2 on 2026-04-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("training", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportstraining",
            name="coach",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.person",
                verbose_name="тренер",
            ),
        ),
        migrations.AddField(
            model_name="sportstraining",
            name="sport",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="training.sport",
                verbose_name="вид спорта",
            ),
        ),
        migrations.AddField(
            model_name="sportstraining",
            name="sporthall",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.sporthall",
                verbose_name="спортзал",
            ),
        ),
    ]
