# Generated by Django 5.2 on 2026-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sportstraining",
            name="weekday",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Воскресенье"),
                    (2, "Понедельник"),
                    (3, "Вторник"),
                    (4, "Среда"),
                    (5, "Четверг"),
                    (6, "Пятница"),
                    (7, "Суббота"),
                ]
            ),
        ),
    ]
