# Generated by Django 5.2 on 2026-04-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_alter_sportstraining_weekday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sport",
            options={
                "verbose_name": "Вид спорта",
                "verbose_name_plural": "Виды спорта",
            },
        ),
        migrations.AlterModelTable(
            name="sport",
            table="sports",
        ),
    ]
